// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Sat Oct 26 12:05:23 2024

HY_207 HY_207_inst
(
	.pin2(pin2_sig) ,	// output  pin2_sig
	.pin3(pin3_sig) ,	// output  pin3_sig
	.pin4(pin4_sig) ,	// output  pin4_sig
	.pin5(pin5_sig) ,	// inout  pin5_sig
	.pin6(pin6_sig) ,	// inout  pin6_sig
	.pin7(pin7_sig) ,	// inout  pin7_sig
	.pin8(pin8_sig) ,	// inout  pin8_sig
	.clk(clk_sig) ,	// input  clk_sig
	.pin14(pin14_sig) ,	// output  pin14_sig
	.pin15(pin15_sig) ,	// output  pin15_sig
	.pin16(pin16_sig) ,	// output  pin16_sig
	.pin17(pin17_sig) ,	// output  pin17_sig
	.pin18(pin18_sig) ,	// output  pin18_sig
	.pin19(pin19_sig) ,	// output  pin19_sig
	.pin20(pin20_sig) ,	// output  pin20_sig
	.pin21(pin21_sig) ,	// output  pin21_sig
	.pin26(pin26_sig) ,	// input  pin26_sig
	.pin27(pin27_sig) ,	// input  pin27_sig
	.pin28(pin28_sig) ,	// input  pin28_sig
	.pin29(pin29_sig) ,	// input  pin29_sig
	.pin30(pin30_sig) ,	// input  pin30_sig
	.pin33(pin33_sig) ,	// input  pin33_sig
	.pin34(pin34_sig) ,	// input  pin34_sig
	.pin35(pin35_sig) ,	// input  pin35_sig
	.pin36(pin36_sig) ,	// output  pin36_sig
	.pin37(pin37_sig) ,	// inout  pin37_sig
	.pin38(pin38_sig) ,	// output  pin38_sig
	.pin39(pin39_sig) ,	// output  pin39_sig
	.pin40(pin40_sig) ,	// output  pin40_sig
	.pin41(pin41_sig) ,	// output  pin41_sig
	.pin42(pin42_sig) ,	// output  pin42_sig
	.pin43(pin43_sig) ,	// output  pin43_sig
	.pin44(pin44_sig) ,	// output  pin44_sig
	.pin47(pin47_sig) ,	// output  pin47_sig
	.pin48(pin48_sig) ,	// output  pin48_sig
	.pin49(pin49_sig) ,	// output  pin49_sig
	.pin50(pin50_sig) ,	// output  pin50_sig
	.pin51(pin51_sig) ,	// input  pin51_sig
	.pin52(pin52_sig) ,	// input  pin52_sig
	.pin53(pin53_sig) ,	// input  pin53_sig
	.pin54(pin54_sig) ,	// inout  pin54_sig
	.pin55(pin55_sig) ,	// inout  pin55_sig
	.pin56(pin56_sig) ,	// inout  pin56_sig
	.pin57(pin57_sig) ,	// inout  pin57_sig
	.pin58(pin58_sig) ,	// output  pin58_sig
	.pin61(pin61_sig) ,	// output  pin61_sig
	.pin62(pin62_sig) ,	// input  pin62_sig
	.pin64(pin64_sig) ,	// inout  pin64_sig
	.pin66(pin66_sig) ,	// inout  pin66_sig
	.pin67(pin67_sig) ,	// inout  pin67_sig
	.pin68(pin68_sig) ,	// inout  pin68_sig
	.pin69(pin69_sig) ,	// inout  pin69_sig
	.pin70(pin70_sig) ,	// input  pin70_sig
	.pin71(pin71_sig) ,	// input  pin71_sig
	.pin72(pin72_sig) ,	// input  pin72_sig
	.pin73(pin73_sig) ,	// output  pin73_sig
	.pin74(pin74_sig) ,	// output  pin74_sig
	.pin75(pin75_sig) ,	// output  pin75_sig
	.pin76(pin76_sig) ,	// output  pin76_sig
	.pin77(pin77_sig) ,	// output  pin77_sig
	.pin78(pin78_sig) ,	// output  pin78_sig
	.pin81(pin81_sig) ,	// output  pin81_sig
	.pin82(pin82_sig) ,	// output  pin82_sig
	.pin83(pin83_sig) ,	// output  pin83_sig
	.pin84(pin84_sig) ,	// output  pin84_sig
	.pin85(pin85_sig) ,	// output  pin85_sig
	.pin86(pin86_sig) ,	// output  pin86_sig
	.pin87(pin87_sig) ,	// output  pin87_sig
	.pin88(pin88_sig) ,	// output  pin88_sig
	.pin89(pin89_sig) ,	// output  pin89_sig
	.pin90(pin90_sig) ,	// output  pin90_sig
	.pin91(pin91_sig) ,	// output  pin91_sig
	.pin92(pin92_sig) ,	// output  pin92_sig
	.pin95(pin95_sig) ,	// output  pin95_sig
	.pin96(pin96_sig) ,	// output  pin96_sig
	.pin97(pin97_sig) ,	// output  pin97_sig
	.pin98(pin98_sig) ,	// output  pin98_sig
	.pin99(pin99_sig) ,	// output  pin99_sig
	.pin100(pin100_sig) ,	// output  pin100_sig
	.pin1(pin1_sig) 	// output  pin1_sig
);

